### ISSUE TITLE
Create first pull request with a scenario from Home Feature.

### ISSUE THREAD

**Issue by sincovschi** [remote-labs-sarl/hire#2]
Create first pull request with feature:
apps/front-e2e/cypress/integration/Home.feature
"home page category link should redirect to the filtering page."

**Comment by sincovschi** [comment]
@AlinaPop2018 good luck!

**Comment by AlinaPop2018** [comment]
Ciao,
Am nevoie de ajutor ca sa pornesc proiectul. Nu reusesc.

Mersi.

**Comment by AlinaPop2018** [comment]
PS C:\Users\utente\Documents\dev\angularPR\daniel\hire> npx nx serve
npx : The term 'npx' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1 char:1+ npx nx serve+ ~~~    + CategoryInfo          : ObjectNotFound: (npx:String) [], CommandNotFoundE     xception    + FullyQualifiedErrorId : CommandNotFoundException
    Il mercoledì 16 novembre 2022 15:19:09 CET, JohnDoeee123 ***@***.***> ha scritto:  
 
 




Hello,
1.Deschizi terminalul in redacina proiectului
2. Rulezi "npx nx serve" , fara ghilimele
3. Accesezi in browser http://localhost:4200/
